#!/usr/bin/env python3
"""Generate quangdang/inc/icons.php from Phosphor Icons (MIT), pinned release.

Two weights are kept: "bold" (UI glyphs: arrows, chevrons, close) and "duotone" (feature icons;
a 20%-opacity layer plus the opaque outline, so the outline alone carries the meaning).

ALIASES maps the names templates already use (the old Lucide names) to Phosphor names, so call
sites keep working. Add a Phosphor name to EXTRA when a new icon is needed, then re-run.

Usage:  python3 dev/icons.py
"""
import os
import re
import time
import urllib.request

VERSION = "2.1.1"  # @phosphor-icons/core
CDN = "https://cdn.jsdelivr.net/npm/@phosphor-icons/core@%s/assets/%%s/%%s.svg" % VERSION
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(REPO, "quangdang", "inc", "icons.php")

ALIASES = {
    "arrow-left": "arrow-left", "arrow-right": "arrow-right", "arrow-up-right": "arrow-up-right",
    "award": "medal", "badge-check": "seal-check", "banknote": "money", "book-open": "book-open",
    "building-2": "buildings", "calendar-check": "calendar-check", "calendar-days": "calendar-dots",
    "check": "check", "chevron-down": "caret-down", "chevron-left": "caret-left",
    "chevron-right": "caret-right", "circle-check": "check-circle",
    "circle-dollar-sign": "currency-circle-dollar", "circle-help": "question",
    "clipboard-list": "clipboard-text", "clock": "clock", "copy": "copy", "droplets": "drop",
    "external-link": "arrow-square-out", "eye": "eye", "facebook": "facebook-logo",
    "flask-conical": "flask", "gift": "gift", "graduation-cap": "graduation-cap",
    "hand-heart": "hand-heart", "heart": "heart", "hourglass": "hourglass", "image": "image",
    "info": "info", "layers": "stack", "leaf": "leaf", "link": "link", "list-checks": "list-checks",
    "mail": "envelope-simple", "map-pin": "map-pin", "menu": "list", "message-circle": "chat-circle",
    "message-circle-more": "chat-circle-dots", "microscope": "microscope", "minus": "minus",
    "navigation": "navigation-arrow", "newspaper": "newspaper", "percent": "percent", "phone": "phone",
    "plus": "plus", "quote": "quotes", "repeat": "repeat", "scan-face": "scan-smiley",
    "search": "magnifying-glass", "share-2": "share-network", "shield-check": "shield-check",
    "smile": "smiley", "sparkles": "sparkle", "star": "star", "stethoscope": "stethoscope",
    "sun": "sun", "syringe": "syringe", "tag": "tag", "timer": "timer", "triangle-alert": "warning",
    "user-round": "user", "users": "users", "x": "x", "zap": "lightning",
}
EXTRA = ["caret-up", "phone-call"]
WEIGHTS = ("bold", "duotone")


def fetch(weight, name):
    suffix = "" if weight == "regular" else "-" + weight
    url = CDN % (weight, name + suffix)
    for attempt in range(4):
        try:
            with urllib.request.urlopen(url, timeout=30) as r:  # noqa: S310 (pinned https URL)
                return r.read().decode("utf-8")
        except Exception:  # retry on proxy/transient errors
            time.sleep(1 + attempt)
    raise SystemExit("could not fetch " + url)


def inner(svg):
    m = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S)
    body = re.sub(r"\s+", " ", m.group(1)).strip()
    return re.sub(r"> <", "><", body)


def php_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    names = sorted(set(ALIASES.values()) | set(EXTRA))
    rows = []
    for name in names:
        parts = ["\t\t\t%s => %s," % (php_str(w), php_str(inner(fetch(w, name)))) for w in WEIGHTS]
        rows.append("\t\t%s => array(\n%s\n\t\t)," % (php_str(name), "\n".join(parts)))
    alias_rows = ["\t\t%s => %s," % (php_str(k), php_str(v)) for k, v in sorted(ALIASES.items())]

    php = """<?php
/**
 * Inline SVG icons: Phosphor Icons %(version)s (MIT, (c) 2020 Phosphor Icons), weights "bold" and "duotone".
 * GENERATED by dev/icons.py. Edit the script, not this file.
 *
 * qd_icon_alias(): names templates use (old Lucide names) => Phosphor names.
 * qd_icon_data():  Phosphor name => weight => inner SVG markup (viewBox 0 0 256 256, fill currentColor).
 *
 * @package QuangDang
 */

defined( 'ABSPATH' ) || exit;

/**
 * Names used by templates mapped to the Phosphor icon that draws them.
 *
 * @return array<string,string>
 */
function qd_icon_alias() {
	return array(
%(aliases)s
	);
}

/**
 * Icon markup keyed by Phosphor name, then weight.
 *
 * @return array<string,array<string,string>>
 */
function qd_icon_data() {
	return array(
%(rows)s
	);
}
""" % {"version": VERSION, "aliases": "\n".join(alias_rows), "rows": "\n".join(rows)}
    open(OUT, "w", encoding="utf-8").write(php)
    print("wrote %s: %d icons x %d weights, %d bytes" % (OUT, len(names), len(WEIGHTS), os.path.getsize(OUT)))


if __name__ == "__main__":
    main()
